-- 계정 변경 EDU/1234
SELECT * FROM TAB
;
DROP TABLE ADDRESSBOOK PURGE
; -- PURGE : 완전삭제
CREATE TABLE ADDRESSBOOK(
	num		NUMBER			PRIMARY KEY,
	name	VARCHAR2(10)	NOT NULL,
	phone	VARCHAR2(15),
	addr	VARCHAR2(70)
);
DROP SEQUENCE num_seq
;
CREATE SEQUENCE num_seq
START WITH 1 INCREMENT BY 1
NOCYCLE NOCACHE
;
INSERT INTO ADDRESSBOOK
VALUES (num_seq.NEXTVAL, 'aaa', '010-111-1111', '서울')
;
INSERT INTO ADDRESSBOOK
VALUES (num_seq.NEXTVAL, 'bbb', '010-222-2222', '울릉도')
;
INSERT INTO ADDRESSBOOK
VALUES (num_seq.NEXTVAL, 'ccc', '010-333-3333', '제주도')
;
SELECT * FROM ADDRESSBOOK
;