CREATE TABLE STUDENT (
	mid		NUMBER			PRIMARY KEY,
	name	VARCHAR2(15)	NOT NULL,
	kor		NUMBER,
	eng		NUMBER,
	mat		NUMBER
);

CREATE SEQUENCE M_MID START WITH 1 INCREMENT BY 1 NOCYCLE NOCACHE
;

INSERT INTO STUDENT VALUES (M_MID.NEXTVAL, '민들래', 90, 88, 75)
;
INSERT INTO STUDENT VALUES (M_MID.NEXTVAL, '진달래', 80, 88, 65)
;
